[package]
name = "discord_bots"
version = "0.1.0"
authors = ["Thomas-QM <thomas@engineeringvirtue.net>"]

[dependencies]
chrono = {version="0.4.6", features=["serde"]}
failure = "0.1.3"
failure_derive = "0.1.3"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_urlencoded = "0.5.3"
reqwest = "0.9.4"